name: stx_data_search
description: Generic search package for collections.
version: 1.0.1

homepage: https://github.com/VolodymyrSydorko/stx_data_search
repository: https://github.com/VolodymyrSydorko/stx_data_search
documentation: https://github.com/VolodymyrSydorko/stx_data_search

environment:
  sdk: '>=2.16.0 <3.0.0'
  
dev_dependencies: 
  flutter_lints: ^1.0.4
