name: stx_data_search
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/VolodymyrSydorko/stx_data_search

environment:
  sdk: '>=2.16.0 <3.0.0'
  
dev_dependencies: 
  flutter_lints: ^1.0.4
